# Dependencies
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Description
title: Jesus M Rueda-Becerril, PhD
logo: /images/Redwood.jpg
# show_downloads: false
name: Jesus M. Rueda-Becerril
description: Welcome to my personal webpage
theme: jekyll-theme-minimal

author:
  email: jm.ruebe@gmail.com
  display_name: jeruebe
  first_name: Jesus
  last_name: Rueda-Becerril

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb

# Permalink and paginate
# permalink: none
# paginate_multiple:
# paginate: 5

# paginate_path: '/blog/page:num/'
#   - paginate: 5
#     paginate_path: '/mula/page:num/'
include: ['_pages']
# relative_permalinks: false

# atom:
#   buildCommand:
#     - bundle
#     - exec
#     - jekyll
#     - serve
#     - --incremental
#     - --draft
